export const CREATE_MATCH = 'CREATE_MATCH';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_FAILURE = 'CREATE_MATCH_FAILURE';

export const FETCH_MATCH_SELECTIONS = 'FETCH_MATCH_SELECTIONS';
export const FETCH_MATCH_SELECTIONS_SUCCESS = 'FETCH_MATCH_SELECTIONS_SUCCESS';
export const FETCH_MATCH_SELECTIONS_FAILURE = 'FETCH_MATCH_SELECTIONS_FAILURE';

export const SAVE_MATCH_SELECTIONS = 'SAVE_MATCH_SELECTIONS';
export const SAVE_MATCH_SELECTIONS_SUCCESS = 'SAVE_MATCH_SELECTIONS_SUCCESS';
export const SAVE_MATCH_SELECTIONS_FAILURE = 'SAVE_MATCH_SELECTIONS_FAILURE';